### ISSUE TITLE
Cannot find module 'primeng'

### ISSUE THREAD

**Issue by Sky4CE** [shlomiassaf/webpack-dll-bundles-plugin#16]
I'm trying to use primeng components wtih DllBundlesPlugin, but when I add 'primeng' into vendor bundle webpack compilation fails with this error:
```
DLL: Checking if DLLs are valid.
npm : { Error: Cannot find module 'primeng'
At line:1 char:1
+ npm run build:dev
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ({ Error: Cannot find module 'primeng':String) 
    [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.resolve (internal/module.js:27:19)
    at DllBundlesControl.getPackageJsonPath 
```

My config is as follows:
```javascript
    plugins: [
        new DllBundlesPlugin({
            bundles: {
                polyfills: [
                    'core-js',
                    {
                        name: 'zone.js',
                        path: 'zone.js/dist/zone.js'
                    },
                    {
                        name: 'zone.js',
                        path: 'zone.js/dist/long-stack-trace-zone.js'
                    }
                ],
                vendor: [
                    '@angular/platform-browser',
                    '@angular/platform-browser-dynamic',
                    '@angular/core',
                    '@angular/common',
                    '@angular/forms',
                    '@angular/http',
                    '@angular/router',
                    'primeng',
                    'rxjs',
                ]
            },
            dllDir: './wwwroot/dist',
            webpackConfig: webpackMerge(commonConfig, {
                devtool: 'cheap-module-source-map',
                plugins: []
            })
        })
    ]
```

I've also tried 'primeng/primeng', but then I get:
`Error: Package name mismatch, Expected primeng/primeng but found primeng `

So, is it possible somehow to use DllBundlesPlugin with PrimeNG ?

**Comment by tsawan** [comment]
I was able to get it to work by using primeng/primeng in the bundle config. Since this plugin tries to match the module name with it's package.json, you also need to change the name in node_modules/primeng/package.json to primeng/primeng. It's not elegant but it works for now.

**Comment by Sky4CE** [comment]
Thanks @tsawan , but that's not an option, moreover it doesn't work for me, even though webpack able to build package with tweaked node_modules/primeng/package.json then I get runtime errors. 
Seems like this plugin isn't ready to use, cuz apart from this problem it totally breaks webpack HMR in my project.

**Comment by nehalist** [comment]
Encountering the same problem. Any solutions?

**Comment by valery-vitko** [comment]
Plugin config has an option to specify module paths explicitly (as you can see in configuration for `zone.js`). Consider trying it instead of plain `'primeng'` string:

```
  vendor: [
    ...
    {
      name: 'primeng',
      path: 'primeng/primeng'
    },
    ...
  ]
```

**Comment by skorunka** [comment]
@valery-vitko Yes, I can confirm, that it solved the issue. Thanks.
