### ISSUE TITLE
context

### ISSUE THREAD

**Issue by maxisam** [shlomiassaf/webpack-dll-bundles-plugin#2]
I think I saw your beta 3. It should be this.options.webpackConfig.context instead.
and add **!** at
```
if (!this.options.context) {
            this.options.webpackConfig.context = process.cwd();
 }
```

Great work , btw

**Comment by shlomiassaf** [comment]
I forgot the `!`, fixed with beta 4, careless blind updates :)

I don't update the webpack config context as it already comes from the user...

**Comment by maxisam** [comment]
I see, you meant to add context as an option, not trying to use the context from webpack

**Comment by shlomiassaf** [comment]
@maxisam That's a different context, the webpack config context is deprecated I think...

**Comment by maxisam** [comment]
huh, it is still there https://webpack.js.org/configuration/entry-context/#context
